version: '3.8'

services:
  web:
    image: nginx:latest
    networks:
      - my_bridge_network
  
  app:
    image: myapp:latest
    networks:
      - my_bridge_network

networks:
  my_bridge_network:
    driver: bridge